### ISSUE TITLE
FCN: This is for testing the flow only, not a valid bug.

### ISSUE THREAD

**Issue by luciazl** [luciazl/Hello-Word#1]
Step:
1. Test
2. Test

Actual Result:
Test

Expected Result:
Test

Additional Information:
1. Test

Configuration Info:
OS:
Build:

Screen Shot:
![img_1829 - copy](https://cloud.githubusercontent.com/assets/25341897/22285520/ee8c98e0-e326-11e6-875f-6bbd94135b39.JPG)

**Comment by Whicky** [comment]
hello Lucia!

**Comment by luciazl** [comment]
Close
